services:
  - type: web
    name: ar-book-server
    env: python
    pythonVersion: 3.11
    nodeVersion: 18.17.0
    buildCommand: "npm install --legacy-peer-deps && pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:5000 server:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
