services:
  - type: web
    name: ar-book-coloured
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
